... 중간생략 ...
# 이 부분을 지정 경로로 설정하면 해당되는 지정 경로로 업로드된 파일들이 저장된다.

# Absolute path to the directory where attachments are stored.
# The default is the 'files' directory in your Redmine instance.
# Your Redmine instance needs to have write permission on this
# directory.
# Examples:
# attachments_storage_path: /var/redmine/files
# attachments_storage_path: D:/redmine/files
attachments_storage_path:
... 중간생략 ...
